import type { MockRole } from "../mock-api/contracts";

export type RouteThemeMode = "light" | "dark";
export type RouteDeviceSet = "desktop" | "mobile";

export type ButtonSpec = {
  testId: string;
  action: "navigate" | "modal-open" | "modal-close" | "submit" | "toggle" | "external";
  expected: {
    urlIncludes?: string;
    appearsTestId?: string;
    disappearsTestId?: string;
  };
};

export type RouteCase = {
  id: string;
  pathTemplate: string;
  path: string;
  requiredRole: MockRole;
  profileMode?: "complete" | "incomplete";
  modeSet: RouteThemeMode[];
  deviceSet: RouteDeviceSet[];
  readyLocator: { kind: "testid" | "text" | "selector"; value: string };
  buttonSpecs: ButtonSpec[];
};

const ALL_MODES: RouteThemeMode[] = ["light", "dark"];
const ALL_DEVICES: RouteDeviceSet[] = ["desktop", "mobile"];

const GENERATION_NAME = encodeURIComponent("59기");
const ROUTES: RouteCase[] = [
  {
    id: "home",
    pathTemplate: "/",
    path: "/",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "home-activities-grid" },
    buttonSpecs: [],
  },
  {
    id: "about",
    pathTemplate: "/about",
    path: "/about",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "about-page" },
    buttonSpecs: [],
  },
  {
    id: "about-photographers",
    pathTemplate: "/about/photographers",
    path: "/about/photographers",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "about-photographers-page" },
    buttonSpecs: [],
  },
  {
    id: "about-recruiting",
    pathTemplate: "/about/recruiting",
    path: "/about/recruiting",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "about-recruiting-page" },
    buttonSpecs: [],
  },
  {
    id: "archive-root",
    pathTemplate: "/archive",
    path: "/archive",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "archive-records-grid" },
    buttonSpecs: [],
  },
  {
    id: "archive-records",
    pathTemplate: "/archive/records",
    path: "/archive/records",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "archive-records-grid" },
    buttonSpecs: [],
  },
  {
    id: "archive-record-detail",
    pathTemplate: "/archive/records/:id",
    path: "/archive/records/act-1",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "record-detail-gallery" },
    buttonSpecs: [],
  },
  {
    id: "archive-exhibitions",
    pathTemplate: "/archive/exhibitions",
    path: "/archive/exhibitions",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "archive-exhibitions-grid" },
    buttonSpecs: [],
  },
  {
    id: "archive-exhibition-detail",
    pathTemplate: "/archive/exhibitions/:id",
    path: "/archive/exhibitions/exh-1",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "exhibition-detail-gallery" },
    buttonSpecs: [],
  },
  {
    id: "linktree",
    pathTemplate: "/linktree",
    path: "/linktree",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "linktree-groups" },
    buttonSpecs: [],
  },
  {
    id: "donate",
    pathTemplate: "/donate",
    path: "/donate",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "후원" },
    buttonSpecs: [],
  },
  {
    id: "auth-pending-approval",
    pathTemplate: "/auth/pending-approval",
    path: "/auth/pending-approval",
    requiredRole: "unverified",
    profileMode: "complete",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "auth-pending-approval-page" },
    buttonSpecs: [],
  },
  {
    id: "auth-sign-in",
    pathTemplate: "/auth/sign-in",
    path: "/auth/sign-in",
    requiredRole: "guest",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "Dashboard 로그인" },
    buttonSpecs: [],
  },
  {
    id: "auth-profile",
    pathTemplate: "/auth/profile",
    path: "/auth/profile",
    requiredRole: "unverified",
    profileMode: "incomplete",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard",
    pathTemplate: "/dashboard",
    path: "/dashboard",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "연영회에 오신 것을 환영합니다." },
    buttonSpecs: [],
  },
  {
    id: "dashboard-profile",
    pathTemplate: "/dashboard/profile",
    path: "/dashboard/profile",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-market",
    pathTemplate: "/dashboard/market",
    path: "/dashboard/market",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-market-new",
    pathTemplate: "/dashboard/market/new",
    path: "/dashboard/market/new",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "market-create-form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-market-detail",
    pathTemplate: "/dashboard/market/:itemId",
    path: "/dashboard/market/market-1",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "필름 카메라" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-market-edit",
    pathTemplate: "/dashboard/market/:itemId/edit",
    path: "/dashboard/market/market-1/edit",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "market-edit-form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings",
    pathTemplate: "/dashboard/settings",
    path: "/dashboard/settings",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-notices",
    pathTemplate: "/dashboard/settings/notices",
    path: "/dashboard/settings/notices",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-notices-new",
    pathTemplate: "/dashboard/settings/notices/new",
    path: "/dashboard/settings/notices/new",
    requiredRole: "vice_president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-notice-detail",
    pathTemplate: "/dashboard/settings/notices/:noticeId",
    path: "/dashboard/settings/notices/notice-1",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-notice-edit",
    pathTemplate: "/dashboard/settings/notices/:noticeId/edit",
    path: "/dashboard/settings/notices/notice-1/edit",
    requiredRole: "vice_president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-linktree",
    pathTemplate: "/dashboard/settings/linktree",
    path: "/dashboard/settings/linktree",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-linktree-new",
    pathTemplate: "/dashboard/settings/linktree/new",
    path: "/dashboard/settings/linktree/new",
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "linktree-create-form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-linktree-detail",
    pathTemplate: "/dashboard/settings/linktree/:linktreeId",
    path: "/dashboard/settings/linktree/linktree-1",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "공식 채널" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-linktree-edit",
    pathTemplate: "/dashboard/settings/linktree/:linktreeId/edit",
    path: "/dashboard/settings/linktree/linktree-1/edit",
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-linktree-item-detail",
    pathTemplate: "/dashboard/settings/linktree/:linktreeId/items/:itemId",
    path: "/dashboard/settings/linktree/linktree-1/items/linktree-item-1",
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "Instagram" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-linktree-item-edit",
    pathTemplate: "/dashboard/settings/linktree/:linktreeId/items/:itemId/edit",
    path: "/dashboard/settings/linktree/linktree-1/items/linktree-item-1/edit",
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-site",
    pathTemplate: "/dashboard/settings/site",
    path: "/dashboard/settings/site",
    requiredRole: "president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-recruiting",
    pathTemplate: "/dashboard/settings/recruiting",
    path: "/dashboard/settings/recruiting",
    requiredRole: "president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "recruiting-plan-save" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-members",
    pathTemplate: "/dashboard/settings/members",
    path: "/dashboard/settings/members",
    requiredRole: "president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-member-detail",
    pathTemplate: "/dashboard/settings/members/:memberId",
    path: "/dashboard/settings/members/user-member",
    requiredRole: "president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "최부원" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-settings-generations",
    pathTemplate: "/dashboard/settings/generations",
    path: "/dashboard/settings/generations",
    requiredRole: "president",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-home",
    pathTemplate: "/dashboard/:generationName",
    path: `/dashboard/${GENERATION_NAME}`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-notices",
    pathTemplate: "/dashboard/:generationName/notices",
    path: `/dashboard/${GENERATION_NAME}/notices`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-notices-new",
    pathTemplate: "/dashboard/:generationName/notices/new",
    path: `/dashboard/${GENERATION_NAME}/notices/new`,
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-notice-detail",
    pathTemplate: "/dashboard/:generationName/notices/:noticeId",
    path: `/dashboard/${GENERATION_NAME}/notices/gnotice-1`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "59기 공지" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-activities",
    pathTemplate: "/dashboard/:generationName/activities",
    path: `/dashboard/${GENERATION_NAME}/activities`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "generation-activities-list" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-activities-new",
    pathTemplate: "/dashboard/:generationName/activities/new",
    path: `/dashboard/${GENERATION_NAME}/activities/new`,
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-activity-detail",
    pathTemplate: "/dashboard/:generationName/activities/:activityId",
    path: `/dashboard/${GENERATION_NAME}/activities/act-1`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "교내 출사" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-activity-edit",
    pathTemplate: "/dashboard/:generationName/activities/:activityId/edit",
    path: `/dashboard/${GENERATION_NAME}/activities/act-1/edit`,
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-exhibitions",
    pathTemplate: "/dashboard/:generationName/exhibitions",
    path: `/dashboard/${GENERATION_NAME}/exhibitions`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "testid", value: "generation-exhibitions-list" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-exhibitions-new",
    pathTemplate: "/dashboard/:generationName/exhibitions/new",
    path: `/dashboard/${GENERATION_NAME}/exhibitions/new`,
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-exhibition-detail",
    pathTemplate: "/dashboard/:generationName/exhibitions/:id",
    path: `/dashboard/${GENERATION_NAME}/exhibitions/exh-1`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "text", value: "정기 사진전" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-exhibition-edit",
    pathTemplate: "/dashboard/:generationName/exhibitions/:id/edit",
    path: `/dashboard/${GENERATION_NAME}/exhibitions/exh-1/edit`,
    requiredRole: "manager",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "form" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-members",
    pathTemplate: "/dashboard/:generationName/members",
    path: `/dashboard/${GENERATION_NAME}/members`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
  {
    id: "dashboard-generation-member-detail",
    pathTemplate: "/dashboard/:generationName/members/:memberId",
    path: `/dashboard/${GENERATION_NAME}/members/user-member`,
    requiredRole: "member",
    modeSet: ALL_MODES,
    deviceSet: ALL_DEVICES,
    readyLocator: { kind: "selector", value: "main h1" },
    buttonSpecs: [],
  },
];

export const routeManifest: RouteCase[] = ROUTES;
